name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install dependencies
      run: sudo apt-get update && sudo apt-get -y install cppcheck  && sudo apt-get -y install bear && sudo apt-get -y install pipx && sudo apt-get -y install libreadline-dev 

    - name : install norminette
      run: pipx install norminette

    - name: build
      run: CC=clang make

    - name: run tests
      run: CC=clang make vtest
